version: '3'
services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: "mysqlsrv"
      MYSQL_DATABASE: "Vestibular"
      MYSQL_USER: "flavio"
      MYSQL_PASSWORD: "password"
    links:
      - mysqlsrv
    depends_on:
      - mysqlsrv
    networks:
      - mysql-compose-network

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_HOST: "mysqlsrv"
      MYSQL_DATABASE: "Vestibular"
      MYSQL_USER: "flavio"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3313:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge